# Generated by Django 5.1.3 on 2024-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white', models.CharField(max_length=100)),
                ('black', models.CharField(max_length=100)),
                ('moves', models.TextField(default='')),
                ('current_turn', models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='white', max_length=10)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], default='ongoing', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serializedboard', models.TextField(default='')),
            ],
        ),
    ]
